### ISSUE TITLE
Command to "fan" topic not received by the gateway

### ISSUE THREAD

**Issue by FulvioSpelta** [magcode/daikin-mqtt#9] opened 2020-06-02 08:26 UTC
Publish commands to "fan" topic such as:
`daikintest/giorno/aircon/fan/set
`
![image](https://user-images.githubusercontent.com/1832999/83497801-4dd70c00-a4bb-11ea-8de3-3550189456df.png)

shows nothing in the gateway log.

**Comment by magcode** [comment] 2020-06-03 19:46
duplicate of #8

**Closed as completed** 2020-06-03 19:46 UTC

**Comment by FulvioSpelta** [comment] 2020-06-04 06:11
Just a comment to be sure that the issue is clear:

The difference with #8 is this:
#8 the posted command is visible in the log but not executed by the split
#9 the command is not visible in the log nor is executed by the split

**Comment by magcode** [comment] 2020-06-04 08:01
Please re-test with the latest version. Thanks for contribution.
